# This is a basic workflow to help you get started with Actions

name: Update Football Predict README

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 0시(UTC)에 실행

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run script
        env:
          FOOTBALLPREDICT_API_KEY: ${{ secrets.FOOTBALLPREDICT_API_KEY }}
        run: python football-api.py

      - name: Commit & Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Auto-update football predict" || echo "No changes to commit"
          git push
